### PR TITLE
[C] add german to language

### PR DESCRIPTION
**Pull request by SecHex**

### CODE REVIEW

**Comment by PaperTurtle** [comment]
This is a nice starting point, do you plan on finishing the translation?

**Comment by SecHex** [comment]
> This is a nice starting point, do you plan on finishing the translation?

The translation is finished?

**Comment by Hangover3832** [comment]
It seems that this is a translation of language/example.json which is probably not in use.

**Comment by PaperTurtle** [comment]
> It seems that this is a translation of language/example.json which is probably not in use.

I agree. I could also provide the german translation if needed. Alternatively @SecHex could complete it too if they want.

**Comment by Hangover3832** [comment]
I also planned to work on this, but please go ahead, awaiting your PR.

**Comment by PaperTurtle** [comment]
Thanks, I will get to work then

**Comment by SecHex** [comment]
i was just a bit lost. Sorry for the useless mr.

**Pull request closed without merging**
