### PR TITLE
Try add mask upload and mask invert feature. 尝试添加上传蒙版、反转蒙版功能

### PR DESCRIPTION
**Pull request by xhoxye**
Add mask upload feature.
The code is from https://github.com/lllyasviel/Fooocus/pull/529
添加蒙版上传功能。
参考代码来自这里，
部分代码已被删除，但它目前是可用的。

### CODE REVIEW

**Comment by xhoxye** [comment]
If there is a mistake, hope someone can help me correct it, I don't have the ability to fix it.
如果有错误，希望有人能帮助我修改，我没有能力修改

**Comment by diaolulu1** [comment]
扩图功能会因为蒙版功能不完善造成bug，在扩图之前随便在原图上用重绘画笔点个小点即可正常扩图。稍后我忙完了再修复bug

**Comment by xhoxye** [comment]
尝试修复和外部扩充绘制配合时出现的问题
_6248.png…]()。


5f6054f3d8b8)

**Comment by R4290N** [comment]
Hi! can you give files and instructions to try your enhancement?

**Comment by xhoxye** [comment]
QQ截图20231206212713

**Comment by citraka** [comment]
> QQ截图20231206212713

This is such a nice enhancement to an already wonderful tool as fooocus, thank you xhoxye.
By the way, there is this useful tool online and free that removes the background of an image and provides also the mask: https://huggingface.co/spaces/Rothfeld/stable-diffusion-mat-outpainting-primer

Also, would it be possible to add to your tool the ability to invert the mask?
Like for example, in playground, allows you to paint a mask and also invert it.
Screenshot 2023-12-09 124856
Thank you

**Comment by xhoxye** [comment]
Try adding a mask inversion feature.
尝试添加蒙版反转功能。
增加一个复选框来决定是否将蒙版反转。

QQ截图20231210194530
QQ截图20231210192025
QQ截图20231210192040

**Comment by citraka** [comment]
Fantastic xhoxye! I tried it and it worked perfectly! Thank you so much! It's so easy now to load and apply perfect masks and also invert them and change the rest of the content!
I would like to mention this free online tool that makes a mask of an image by removing the background: https://huggingface.co/spaces/ECCV2022/dis-background-removal
Great enhanceent, thanks :-)

**Comment by R4290N** [comment]
Hello, xhoxye! 
thank you very much for your initiative! everything was working fine, but now Fooocus got an update and your async_worker.py and webui.py make it inoperable,Fooocus now doesn't start after replacing the files. Can you please fix this?

**Comment by xhoxye** [comment]
> Hello, xhoxye! 你好，xhoxye！ thank you very much for your initiative! everything was working fine, but now Fooocus got an update and your async_worker.py and webui.py make it inoperable,Fooocus now doesn't start after replacing the files. Can you please fix this?非常感谢您的倡议！一切正常，但现在 Fooocus 得到了更新，您的async_worker.py和 webui.py 使其无法运行，Fooocus 现在在替换文件后无法启动。你能解决这个问题吗？

Please download a new file to replace.

**Comment by R4290N** [comment]
> > Hello, xhoxye! 你好，xhoxye！ thank you very much for your initiative! everything was working fine, but now Fooocus got an update and your async_worker.py and webui.py make it inoperable,Fooocus now doesn't start after replacing the files. Can you please fix this?非常感谢您的倡议！一切正常，但现在 Fooocus 得到了更新，您的async_worker.py和 webui.py 使其无法运行，Fooocus 现在在替换文件后无法启动。你能解决这个问题吗？
> 
> Please download the new files to replace.

wow! thanx!

**Comment by hexcreator** [comment]
This would be a game changer if added.

**Comment by citraka** [comment]
Dear xhoxye, the invert mask feature does not work. When I upload a mask on the mask window of fooocus (which by the way has a typo in its title " Drag *inapint* mask...") and select the "Invert Mask" button, nothing happens, generated images still use the original mask.
 Of course is not such a big problem, I just have to turn the mask to negative using a local simple app, and reupload it, but still, it would be more functional if it could all be done with your nice extension.  Can you please look at it? Thank you!

**Comment by xhoxye** [comment]
> Dear xhoxye, the invert mask feature does not work. When I upload a mask on the mask window of fooocus (which by the way has a typo in its title " Drag _inapint_ mask...") and select the "Invert Mask" button, nothing happens, generated images still use the original mask. Of course is not such a big problem, I just have to turn the mask to negative using a local simple app, and reupload it, but still, it would be more functional if it could all be done with your nice extension. Can you please look at it? Thank you!

Because inverting only works with hand-drawn masks

**Comment by citraka** [comment]
Oh, I see, ok then.  As a matter of fact I just tried it with a hand-drawn mask and it does actually works as intended. 
Yes, local programs can easily revert the desired mask.
One question: Every time there is an update of fooocus, the two files modified by you are overwritten by the original ones, then need to again be replaced by yours. Is there a way to avoid this?
Thank you.

**Comment by xhoxye** [comment]
> Oh, I see, ok then. As a matter of fact I just tried it with a hand-drawn mask and it does actually works as intended. Yes, local programs can easily revert the desired mask. One question: Every time there is an update of fooocus, the two files modified by you are overwritten by the original ones, then need to again be replaced by yours. Is there a way to avoid this? Thank you.

Unless the author merges the request.

**Comment by citraka** [comment]
Ok, got it. Thanks.

**Comment by Gueriero** [comment]
How can I install this, can you tell me? =) Very useful feature.

**Comment by xhoxye** [comment]
> How can I install this, can you tell me? =) Very useful feature.

https://github.com/xhoxye/Fooocus-up_mask/ 
Download the two files I mentioned and overwrite them to their original places.

**Comment by xhoxye** [comment]
I'm going to close this request, check out this branch https://github.com/xhoxye/Fooocus-up_mask/tree/Fooocus_mask_enhance for the same functionality.

**Pull request closed without merging**
