### PR TITLE
Jpg config image extension

### PR DESCRIPTION
**Pull request by eddyizm**
[Added]
feature: added flag, config and ui update for image extension change)[feature: added flag, config and ui update for image extension toggle.

https://github.com/lllyasviel/Fooocus/issues/1789

image

image
image

### CODE REVIEW

**Review by mashb1t — CHANGES_REQUESTED** [review]
Thank you for the implementation.
The config should only be read on app start and not be adjusted during runtime, as this is a global setting.
For UI elements Fooocus currently uses the AsyncJob object, which contains an array of parameters and which is introducing isolation per user/session. Using your approach (config) leads to User 1 updating the output extension also for User 2, who might not be aware / is not made aware of in the UI that the change happened and this way the feature isn't usable in isolation.

This is why i'd propose to add the UI element to the ctrls in webui.py, add a pop() call in async_worker.py and hand it over to the private_logger.py's log() method as a parameter. The radio buttons should also only be shown/interwctive when history log is enabled (see args).
The config is useful and can still be used as default for the instance.

What do you think?

**Comment by eddyizm** [comment]
Hi thanks for the feedback and clarification. Did not realize the config was global so thanks for pointing that out. 
Your suggestions seem reasonable and will give it a go this evening. Appreciate the guidance. New to gradio so this seemed like a good entry point to be able to contribute.

**Comment by RodTDai** [comment]
This is awsome guys, thanks for the work you are all doing.

**Comment by eddyizm** [comment]
Updated with the changes requested. Please let me know if I missed something.

**Review by mashb1t — APPROVED** [review]
@eddyizm i've fixed a bug (missing extension param), added webp support and adjusted the label, as the label "Image Extension" could be misunderstood as images shown in the webui are still always png (see issue https://github.com/lllyasviel/Fooocus/issues/1421). The wording is still not 100% perfect, feel free to adjust to your liking.

Comparison between output formats, incl. webp (same seed & settings):
image

What do you think, should we integrate the proposed solution of https://github.com/lllyasviel/Fooocus/issues/1421 to this feature?

**Comment by eddyizm** [comment]
@mashb1t I agree the naming is not correct. by using image extension we are implying format which it looks like originally I was just changing the naming convention, so more like image naming extension or file extension. When I was changing it I was looking at the gradio docs because there should really be some type of mouse over with a not or a star to say "this does not change the actual creation or compression logic, just simply changes the file extension for convenience" or something to that effect. 

Although after seeing the outputs, it does appear to be affecting the size of the file. 

Good catch on the log parameter, seems like I had it in there at some point and backed it out. 

Everything else looks good to me!

**Comment by mashb1t** [comment]
@eddyizm functionality from https://github.com/lllyasviel/Fooocus/pull/1932 has been merged, works perfectly for me. Now also the preview / final images in gradio do have the selected file extension.
Maybe we can rename the label / field to "File Extension", as this plainly states what it is (both gradio and outputs).

Please check, happy to hear your feedback!

**Comment by eddyizm** [comment]
Looks good to me. That last label change is perfect!

**Comment by mashb1t** [comment]
@eddyizm A label and naming even better describing what it is is "Output Format". Hope this is also ok for you.

**Comment by eddyizm** [comment]
Yup makes more sense. I was thinking about changing it as well. Good call.

**Comment by mashb1t** [comment]
@eddyizm fyi now that https://github.com/lllyasviel/Fooocus/pull/1940 has fully been implemented i've also added EXIF metadata handling for jpg and webp, see https://github.com/mashb1t/Fooocus/commit/b281375ce26bd1f888c51e9e6b1ca91476172f45

**Comment by eddyizm** [comment]
This bad boy keeps getting bigger and bigger!

**Comment by mashb1t** [comment]
@eddyizm would it be ok for you if i add myself as the committing author?
13/18 commits were done my be and I've already integrated EXIF data handling for jpg and webp. 
ofc. adding you as co-author

**Comment by eddyizm** [comment]
@mashb1t sure. No problem at all!

**Pull request merged**
