### PR TITLE
add nsfw image censoring via config and checkbox

### PR DESCRIPTION
**Pull request by mashb1t**
activatable via config, uses CompVis/stable-diffusion-safety-checker

closes https://github.com/lllyasviel/Fooocus/issues/950

### CODE REVIEW

**Comment by mashb1t** [comment]
now has config path support as mentioned in https://github.com/lllyasviel/Fooocus/pull/1418

**Comment by R080T** [comment]
guys when thiss will be ready to pull? thanks a lot, appreciate ur job

**Comment by mashb1t** [comment]
> guys when will be this ready to pull? thanks a lot, appreciate ur job

@R080T Waiting for the review, probably mid/end of January as mentioned in https://github.com/lllyasviel/Fooocus/blob/8e62a72a63b30a3067d1a1bc3f8d226824bd9283/update_log.md?plain=1#L1

**Comment by R080T** [comment]
Thanks guys, I will be also available for testing as I work as a qa automation engineer for 3 years, feel free to contact me if you’re interested. Regards,RobiOn 31 Dec 2023, at 00:31, Manuel Schmid ***@***.***> wrote:﻿

guys when will be this ready to pull? thanks a lot, appreciate ur job

@R080T Waiting for the review, probably mid/end of January as mentioned in https://github.com/lllyasviel/Fooocus/blob/8e62a72a63b30a3067d1a1bc3f8d226824bd9283/update_log.md?plain=1#L1

**Comment by ke1ne** [comment]
Any plans to merge? Seems to be useful. Thanks

**Comment by Msumri** [comment]
Hey im trying to use the censor but im not sure how to add it to my file i created censor .py and add the lines on the other files but im still able to generate nsfw

**Comment by mashb1t** [comment]
@Msumri please check if you've activated the feature either using the config or the checkbox in the developer debug mode.

**Comment by Msumri** [comment]
> config

how do i activate it using config. im sorry im new to all this

**Comment by Msumri** [comment]
i activated it but im still able to generate NSFW

**Comment by Msumri** [comment]
> @Msumri first of all: it's important to note that you can activate this feature by using either config or checkbox.
> 
> Second: is the text "Checking for NSFW content" shown as last step of each image generation? If not, ensure you have applied the necessary code adjustments to all 8 affected files.
> 
> You can go to https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb and replace the content of the playbook with the following code to spin up a Colab instance with all changes of this feature branch:
> 
> ```
> !pip install pygit2==1.12.2
> %cd /content
> !git clone --branch feature/add-nsfw-filter https://github.com/mashb1t/Fooocus.git
> %cd /content/Fooocus
> !python entry_with_update.py --share
> ```
> 
> If this works you've missed some changes (i've already double checked, works fine for me after checking the checkbox "Black Out NSFW").
> 
> Screenshot_20240214-203010

Thanks it worked

**Comment by mashb1t** [comment]
fyi I was able to remove the dependency of diffusers by extracting the needed classes into extras.

**Comment by PrinceDisant** [comment]
**Description:**

We have successfully integrated the Fooocus API and are now attempting to incorporate NSFW models into our API built from the repo-- [Fooocus-API](https://github.com/mrhan1993/Fooocus-API). We have added the new models by replacing the existing folders in our repository with `extras`, `idm_patched`, `models`, `modules`, `presets`, `sdxl_styles`, `wildcards`, `args_manager.py`, and `fooocus_version.py`. We currently have an issue where the app does not generate any images.

**Expected Behavior:**
The new NSFW models should load within a reasonable time frame and generate images with the integrated nsfw code.

**Actual Behavior:**
The models take an excessively long time to load and often do not load at all.

**Attachments:**
Screen recording

**Additional Context:**
We are using the following environment setup:
- OS: Ubuntu 22.04 Ampere A100 (40 GB GPU memory)
- Python Version: 3.10

**Comment by mashb1t** [comment]
@PrinceDisant please open an issue / discussion in Fooocus-API repository as this as nothing to do with Fooocus, where the feature has been implemented in develop and is working correctly in 2.4.0-RC1/2 as well as in [my fork](https://github.com/mashb1t/Fooocus).

**Comment by PrinceDisant** [comment]
@mashb1t Thank you for the prompt response, I will certainly open an issue there.
I implemented your code for the foocus library into my foocus api, but it didnt work.
I did it as there is no default NSFW for the foocus api.

**Pull request merged**
