### PR TITLE
198 wildcards files

### PR DESCRIPTION
**Pull request by tiwentichat**
add 198 files to wildcards file;
they are from this repo: https://github.com/mattjaybe/sd-wildcards

### CODE REVIEW

**Review by lllyasviel — APPROVED** [review]

**Comment by tiwentichat** [comment]
> @tiwentichat is it possible to remove all files begin with "artist" since they seem to cause historical problems in automatic's projects and some issues outside the community
> 
> @MoonRide303 merge if necessary ( after the above resolved

sure, I would remove them now,

**Comment by tiwentichat** [comment]
> @tiwentichat is it possible to remove all files begin with "artist" since they seem to cause historical problems in automatic's projects and some issues outside the community
> 
> @MoonRide303 merge if necessary ( after the above resolved

Done. Files began with artist have been deleted, except the artist.txt.

By the way, would you like to add the function of Random Prompt to Fooocus? 
That looks cool.
I tried that on RuinedFooocus, very great idea.

**Comment by MoonRide303** [comment]
@lllyasviel @tiwentichat While adding more wildcards sounds good, I'd rather opt for doing it slower (1 by 1), and add only high quality wildcards. It would be good to know for every single wildcard how it was constructed, and that it offers resonable coverage of given subject. If we take it all at once without proper review we can easily pollute wildcards folder with low quality content.

For example focal-length.txt from this pull request looks like this:
```
4mm - 14mm  focal length
Fisheye focal length
14mm - 35mm  focal length
Wide angle focal length
35mm - 85mm  focal length
Standard focal length
85mm - 135mm
Short telephoto focal length
135mm+ focal length
Medium telephoto focal length
300mm+ focal length
Macro
Macro focal length
```

Issues:
- not standardized (sometimes numeric, sometimes names),
- double spaces,
- including "focal length" (other wildcards don't have it, like "color.txt" don't have "red color" line),
- unknown source / methodology.

I'd rather use some reliable source of commonly use focal lengths, and made something like that:
```
14mm
20mm
24mm
28mm
35mm
40mm
50mm
85mm
100mm
135mm
200mm
300mm
400mm
500mm
600mm
800mm
```
It's based on [Canon EF Mount Prime list](https://www.canon-europe.com/lenses/prime-lenses/), and I picked Canon as biggest player on digital camera market (according to [DPReview article from 2021](https://www.dpreview.com/news/9756677755/nikkei-canon-sony-made-up-70-of-the-camera-market-in-2020), based on Nikkei report). This way people could add to their prompts sometime like `taken with __focal-length__ lens` and it could match with metadata from real lens, that could be found in training sets made of real photos.

**Comment by MoonRide303** [comment]
Another issue: I've looked into description of [sd-wildcards](https://github.com/mattjaybe/sd-wildcards) repo, and it seems those wildcards were created using ChatGPT - so there is a high change they won't be complete and factually correct, because ChatGPT (as of GPT-4) still hallucinates pretty often.

**Comment by Pdonor** [comment]
A small suggestion is that up until now, the app has been something you could safely download onto a school computer. Some of those NSWF wildcards would change that. I don't want some art teacher getting fired when a file called "BDSM-Type.txt" downloads onto the school computer as soon this pull request is merged.

**Comment by tiwentichat** [comment]
> @lllyasviel @tiwentichat While adding more wildcards sounds good, I'd rather opt for doing it slower (1 by 1), and add only high quality wildcards. It would be good to know for every single wildcard how it was constructed, and that it offers resonable coverage of given subject. If we take it all at once without proper reviews we can easily pollute wildcards folder with low quality content.
> 
> For example focal-length.txt from this pull request looks like this:
> 
> ```
> 4mm - 14mm  focal length
> Fisheye focal length
> 14mm - 35mm  focal length
> Wide angle focal length
> 35mm - 85mm  focal length
> Standard focal length
> 85mm - 135mm
> Short telephoto focal length
> 135mm+ focal length
> Medium telephoto focal length
> 300mm+ focal length
> Macro
> Macro focal length
> ```
> 
> Issues:
> 
> * not standardized (sometimes numeric, sometimes names),
> * double spaces,
> * including "focal length" (other wildcards don't have it, like "color.txt" don't have "red color" line),
> * unknown source / methodology.
> 
> I'd rather use some reliable source of commonly used focal lengths, and made something like that:
> 
> ```
> 14mm
> 20mm
> 24mm
> 28mm
> 35mm
> 40mm
> 50mm
> 85mm
> 100mm
> 135mm
> 200mm
> 300mm
> 400mm
> 500mm
> 600mm
> 800mm
> ```
> 
> It's based on [Canon EF Mount Prime list](https://www.canon-europe.com/lenses/prime-lenses/), and I picked Canon as biggest player on digital camera market (according to [DPReview article from 2021](https://www.dpreview.com/news/9756677755/nikkei-canon-sony-made-up-70-of-the-camera-market-in-2020), based on Nikkei report). This way people could add to their prompts something like `taken with __focal-length__ lens` and it could match with metadata from real lens, that could be found in training sets made of real photos.

Professional and Great response @MoonRide303 , I would do more work on the standardization and reliable sources

**Comment by tiwentichat** [comment]
> A small suggestion is that up until now, the app has been something you could safely download onto a school computer. Some of those NSWF wildcards would change that. I don't want some art teacher getting fired when a file called "BDSM-Type.txt" downloads onto the school computer as soon this pull request is merged.

Yes, That's a big issue! I found some files is about sex... 
More work would be done before next Pull
Thanks for your comment, @Pdonor

**Comment by MoonRide303** [comment]
@tiwentichat Okay, then - I will close this pull request without merging, and let's go quality rather than quantity way - each wildcard (or small set of wildcards, if they would be about same subject / concept) as single pull request, with clean information about source and/or methodology (best if it would be explainable and reproducible - so another person using same logic would end up with the same list of options in given wildcard).

We can also open up discussion on adding more wildcards first (prior to doing pull requests) - so maybe others could both throw some more ideas, and maybe also notice more potential issues (like what @Pdonor pointed it out - while I don't mind NSFW wildcards personally, we also should take into account that it could cause troubles for people who would like to use Fooocus in school or at work).

**Comment by MoonRide303** [comment]
I've added discussion on enhancing wildcards list here: https://github.com/lllyasviel/Fooocus/discussions/741.

**Comment by tiwentichat** [comment]
> I've added discussion on enhancing wildcards list here: #741.

Sure. New discussion is helpful.

**Pull request closed without merging**
