### PR TITLE
update base model Juggernaut XL from v6 to v8

### PR DESCRIPTION
**Pull request by mashb1t**
JuggernautXL v8 has finally been released yesterday (06.01.2024) and it significantly boosts hand/feet accuracy.
The model download URL might (and probably should due to higher speeds) also be changed to lllyasviel huggingface namespace.

Links:
* https://civitai.com/models/133005?modelVersionId=288982
* https://www.reddit.com/r/StableDiffusion/comments/18fta92/juggernautxl_v8_early_training_hand_shots/

Closes https://github.com/lllyasviel/Fooocus/issues/1701

### CODE REVIEW

**Comment by siriume** [comment]
a cat with Seed 2677400719445691677

> JuggernautXL v8 has finally been released yesterday (06.01.2024) and it significantly boosts hand/feet accuracy. The model download URL might (and probably should due to higher speeds) also be changed to lllyasviel huggingface namespace.

The difference between v8 and v6/v7 is a bit big.

| Prompt | Seed | v8 | v7 | v6 |
| - | - | - | - | - |
| `a cat` | 2677400719445691677 | acat_v8 | acat_v7 | acat_v6 |
| `1gril` | 3311663392605993986 | 1girl_v8 | 1girl_v7 | 1girl_v6 |

**Comment by diaolulu1** [comment]
The portion of the URL you modified (type=Model&format=SafeTensor&size=full&fp=fp16) is being treated as code to execute, which is causing errors. You only need the initial part of the URL for the download, like this:
"juggernautXL_v8Rundiffusion.safetensors": "https://civitai.com/api/download/models/288982"

**Comment by mashb1t** [comment]
@diaolulu1 thank you for the hint, code has been adjusted accordingly

**Comment by poor7** [comment]
Try it
https://huggingface.co/Dremmar/juggernaut_v8/resolve/main/juggernautXL_v8Rundiffusion.safetensors

**Comment by mashb1t** [comment]
Resolved as of https://github.com/lllyasviel/Fooocus/commit/3b1cd376317228c153dbd06f4dc1907a424c6eda#diff-4859ea4f0b0c497b49d2ae22c0226cd1a1f2cd72efaf987490495a4817361115R2

**Pull request closed without merging**
