### PR TITLE
Create ru.json

### PR DESCRIPTION
**Pull request by aolko**
[i18n] ru_RU translation

### CODE REVIEW

**Comment by ke1ne** [comment]
Russia is a terrorist state!

**Comment by f242** [comment]
@ke1ne @artemsvit If you were more educated, you would know that Russian language is not only Russia. More than 250 million people speak the language. Russia's population is about 140 million.

**Comment by ke1ne** [comment]
> @ke1ne @artemsvit If you were more educated, you would know that Russian language is not only Russia. More than 250 million people speak the language. Russia's population is about 140 million.

Normalization of genocider is unacceptable

**Comment by LeMs777** [comment]
> > @ke1ne @artemsvit If you were more educated, you would know that Russian language is not only Russia. More than 250 million people speak the language. Russia's population is about 140 million.
> 
> Normalization of genocider is unacceptable

We are talking about localization of the application here. You've probably mistaken this place for some political or news forum

**Comment by aolko** [comment]
continued: #2088

**Pull request closed without merging**
