### PR TITLE
Fooocus mask enhance, mask upload and invert.蒙版增强功能，上传蒙版、反转手涂蒙版

### PR DESCRIPTION
**Pull request by xhoxye**
Functional descriptions, like this link https://github.com/lllyasviel/Fooocus/pull/1126
Fooocus mask enhance, mask upload and invert.蒙版增强功能，上传蒙版、反转手涂蒙版
I closed the original request and copied the code to a branch, and my main branch was used to incorporate various enhancements
我关闭了原先的请求，把代码复制一个分支，我的主分支用来合并各种功能增强。
现在请参考这个地址
https://github.com/xhoxye/Fooocus-up_mask/tree/Fooocus_mask_enhance

Closes https://github.com/lllyasviel/Fooocus/issues/1036

### CODE REVIEW

**Comment by metercai** [comment]
@xhoxye, 非常好的增强，SimpleSDXL能合并这个增强分支吗？不太会整这种分支的事儿😭

**Comment by xhoxye** [comment]
> @xhoxye, 非常好的增强，SimpleSDXL能合并这个增强分支吗？不太会整这种分支的事儿😭

可以的

**Comment by simartem** [comment]
which files to replace to get this functionality ? I changed 2 files (webui.py and async_worker.py).. Fooocus doesnt seem to start.

image

**Comment by xhoxye** [comment]
> which files to replace to get this functionality ? I changed 2 files (webui.py and async_worker.py).. Fooocus doesnt seem to start.
> 
> image

You downloaded the wrong file.

**Comment by SerhiiSfr** [comment]
can you, please, write a code to modify official version

**Comment by xhoxye** [comment]
> can you, please, write a code to modify official version

What do you mean? I, um, modified it based on the official version.

**Comment by SerhiiSfr** [comment]
# Replace only two files with the ones from the new repository
!wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/webui.py -O {HOME_FOLDER}/Fooocus/webui.py
!wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/modules/async_worker.py -O {HOME_FOLDER}/Fooocus/modules/async_worker.py
I use kaggle and it not work((

**Comment by xhoxye** [comment]
> Replace only two files with the ones from the new repository仅将两个文件替换为新存储库中的文件 !wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/webui.py -O {HOME_FOLDER}/Fooocus/webui.py ！wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/webui.py-O {HOME_FOLDER}/Foocus/webui.py !wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/modules/async_worker.py -O {HOME_FOLDER}/Fooocus/modules/async_worker.py ！wget https://github.com/xhoxye/Fooocus-up_mask/blob/Fooocus_mask_enhance/modules/async_worker.py-O {HOME_FOLDER}/Foocus/modules/Fooc_worker.py I use kaggle and it not work(( 我用kaggle和它不工作（（

I tested it just now. The merger works normally. There is no problem in using it.
QQ截图20231230223949
QQ截图20231230223809
QQ截图20231230223817

**Comment by simartem** [comment]
I did the same things before but it failed to run Fooocus, so i started the GUI without update.
After replacing the 2 files stated here  :

https://raw.githubusercontent.com/xhoxye/Fooocus-up_mask/Fooocus_mask_enhance/webui.py
https://raw.githubusercontent.com/xhoxye/Fooocus-up_mask/Fooocus_mask_enhance/modules/async_worker.py

I started the GUI without update with following custom run2.bat edit : 

image

And it worked..
Thank you very much for this ability in focus. I appreciate the effort of the developers.

**Comment by sanebg** [comment]
Mask feature is compleately broken. If I add a object and a mask and try to change the background by inverting the mask it gives me faulty results. The same principle and technique works like a charm in A1111. Any ideas?

**Comment by xhoxye** [comment]
> Mask feature is compleately broken. If I add a object and a mask and try to change the background by inverting the mask it gives me faulty results. The same principle and technique works like a charm in A1111. Any ideas?

QQ截图20240127190942

**Pull request merged**
