### PR TITLE
Styles samples

### PR DESCRIPTION
**Pull request by docppp**
This PR adds "Styles samples" site with images generates with a very basic prompt - "cat" in every available style, so user can easily compare them without a need to generate images beforehand.

### CODE REVIEW

**Review by mashb1t — CHANGES_REQUESTED** [review]
All of these image files are ~ 1.2 MB (avg) => 331.2 MB to additionally check out for every installation of Fooocus, which will drastically increase the overhead.
Let's just link to https://github.com/lllyasviel/Fooocus/discussions/143 as proposed in https://github.com/lllyasviel/Fooocus/issues/1743#issuecomment-1877077821 => no additional files to be downloaded on style changes, much more dynamic as we can update the style preview images on the fly.

**Comment by docppp** [comment]
I dont think that 300 MB would be such a huge issue, since Fooocus users already have to download gigabytes of data in models during first startup. And those pictures are not supposed to change, so git will leave them alone. 
Maybe if i cut the size of every picture by a half? What do you think?

**Comment by poor7** [comment]
>Maybe if i cut the size of every picture by a half? What do you think?
Reduce it by at least 10 times. For most pictures, nothing will change, even if their size is reduced by 50-80 times.

**Comment by docppp** [comment]
> > Maybe if i cut the size of every picture by a half? What do you think?
> 
> Reduce it by at least 10 times. For most pictures, nothing will change, even if their size is reduced by 50-80 times.

Thanks for the tip, total size is reduced to ~20 MB.

**Comment by kyeno** [comment]
Btw, that's not exactly mouse over style preview. :)

**Comment by mashb1t** [comment]
@kyeno mouseover preview has been implemented in https://github.com/lllyasviel/Fooocus/pull/1762
@docppp please have a look at the referenced PR and check if you can combine your changes or close one of them

**Comment by kyeno** [comment]
@mashb1t BEAUTIFUL! I will test it soon.
I made a quick fork that integrates a few more PRs altogether: https://github.com/kyeno/Fooocus/tree/multimerge

Not doing a PR out of it as it'll be rather huge and non-atomic, but most of this stuff is available here anyway.

**Comment by mashb1t** [comment]
@kyeno [me too](https://github.com/mashb1t/Fooocus?tab=readme-ov-file#fooocus---mashb1t-improvements), but i fear that when the PRs of this repository are starting to pile up the community will scatter in their own forks though 😐

**Comment by docppp** [comment]
@mashb1t PR made by @crohrer is great, but I would leave "Style Samples" page as well, so user can check exactly how image was generated with all fooocus settings. For me, at least, it seems very useful.

**Comment by mashb1t** [comment]
@docppp in the end i'm not the one to decide this, but i find both useful. If you agree you can go ahead and merge the changes of the other PR into this one. Please keep in mind that the filenames have changed to 1:1 reflect the style labels.

**Comment by hswlab** [comment]
The list becomes somewhat confusing after you have tried out different styles, as the labels seem to be sorted according to their last use. Is it possible to deactivate this function or perhaps even group them, as in the following example?
image

You could keep the HTML structure and just add another label for the title.
image

**Style for displaying in 2 columns**
```
#component-99 .wrap[data-testid="checkbox-group"] {
  display: flex;
  flex-direction: column;
}

#component-99 .wrap[data-testid="checkbox-group"] label {
  display: none;
}
```

**Comment by mashb1t** [comment]
@hswlab changing the appearance of the whole list is not part of this PR.
I've disabled the style sorting in my fork, please check out the code at https://github.com/mashb1t/Fooocus/blob/main/modules/style_sorter.py#L40 and below to disable the behaviour to sort the list by last used (persistent). This still keeps the position change on checkbox activation though, which i intended to remain.

**Pull request closed without merging**
