### PR TITLE
feat: add metadata to images

### PR DESCRIPTION
**Pull request by mashb1t**
Resolves https://github.com/lllyasviel/Fooocus/issues/241 + #1996
Merge https://github.com/lllyasviel/Fooocus/pull/1932 to also enable metadata in images in the browser, not only images in the outputs folder.

This feature is in contrast to https://github.com/lllyasviel/Fooocus/discussions/160 and might not be merged, but at least if offers the functionality to whoever wants to use it locally, as there was demand for it.

I've implemented both a Fooocus (json) and A1111 (plain text) meta data scheme, where the latter is 100% compatible with A1111 and Civitai, but can not be used to reproduce the image outside of Fooocus, as there are so many improvements and special things happening in Fooocus it's just not applicable anywhere else.

The A1111 meta data scheme is based on [A1111 infotext handling](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/cf2772fab0af5573da775e7437e6acdca424f26e/modules/processing.py#L672-L700) and i've re-implemented the style resolution feature to extract styles and check the corresponding styles checkboxes.

Both schemes might be extended in the future.

This feature also introduces various code optimisations such as extraction of Performance and Steps enums as well as centralisation of values for ControlNet count and LoRA count.

<details><summary>Gradio (setting in Developer Debug Mode)</summary>
<p>

Default is Fooocus Scheme
image

</p>
</details> 

<details><summary>Config options</summary>
<p>

    "default_save_metadata_to_images": true,
    "default_metadata_scheme": "a1111",
    "metadata_created_by": "mashb1t"

</p>
</details> 

<details><summary>Arg --disable-metadata</summary>
<p>

 `--disable-metadata` completely prevents metadata processing and output in Gradio

</p>
</details> 

<details><summary>Metadata Reader</summary>
<p>

1. open Image Input > Metadata tab
2. drag & Drop image to image upload
3. automatic preview of image metadata
4. apply metadata to Gradio inputs on button click

Fooocus scheme
Screenshot 2024-01-29 at 15 13 17

A1111 scheme
Screenshot 2024-01-29 at 15 09 52

</p>
</details> 

<details><summary>Metadata in files</summary>
<p>

Speed Fooocus scheme
image

LCM A1111 scheme (yes, with negative prompt, because it technically exists but doesn't have an influence)
image

Speed A1111 scheme
image

</p>
</details> 

<details><summary>Civitai</summary>
<p>

Speed Fooocus scheme
image

LCM A1111 scheme
image

image

Speed A1111 scheme
image

image

</p>
</details>

### CODE REVIEW

**Comment by lllyasviel** [comment]
will take a look late Jan / early Feb

**Comment by Eleksar387** [comment]
I really like this implementation. I haven't using Fooocus anymore just because I do want my images to have the generation data included. However it doesn't seem to work for me. I merged it and also checked the checkbox then but neither json or automatic1111 seems to work. Still no image data. No idea what I am doing wrong.

**Comment by mashb1t** [comment]
@Eleksar387 Metadata will only be added to images in the output folder (not in browser) until https://github.com/lllyasviel/Fooocus/pull/1932 is merged

**Comment by Eleksar387** [comment]
@mashb1t Understood. That's what I did. As I see the additonal checkbox in the UI I assumed I've merged it correctly. I use [Diffusion Toolkit](https://github.com/RupertAvery/DiffusionToolkit) as an image viewer that also displays prompt data. If I check the add metadata button in Fooocus the images do not even appear in this image browser. They do appear if I uncheck it. 
I am not saying it's not working. Maybe I am doing something wrong. It would be phantastic if this would be added to Fooocus. So it's the users choice.

**Comment by mashb1t** [comment]
@Eleksar387 the default fooocus metadata format i used is probably not compatible with anything else as it's just a json string in the pnginfo. You might have to use the A1111 format to establish compatibility to their scanner, see https://github.com/RupertAvery/DiffusionToolkit/blob/master/Diffusion.Scanner/MetadataScanner.cs.
I am not using and have never used Diffusion Toolkit, but the A1111 metadata scheme is compatible with all A1111 metadata readers as it uses the exact same format.
Please let me know which scheme you used and if it works when selecting A1111.

**Comment by Eleksar387** [comment]
@mashb1t I just checked it again. If I tick "Save Metadata to Images > Automatic1111" the images don't even appear in Diffusion Toolkit. Same if I tick "Fooocus (json)". Although in both cases the images are created and in the folder. But no txt file. If I uncheck "Save Metadata to Images" the images do appear in Diffusion Tookit - but of course without metadata.

**Comment by mashb1t** [comment]
Seems like an issue for [their repository](https://github.com/RupertAvery/DiffusionToolkit), at least they do not display then images with different metadata.

> Please open the png in a text editor and check if metadata is present (in the first few lines of binary code)

Please confirm the metadata exists in the file.

**Comment by VictorZakharov** [comment]
There is a quite a bit of work in here. Thank you for doing it.
Is there a plan to merge all this to main? @mashb1t

**Comment by mashb1t** [comment]
@VictorZakharov yes.
The plan is not only to merge this PR, but also all of my various others, see https://github.com/lllyasviel/Fooocus/pulls/mashb1t.

**Comment by VictorZakharov** [comment]
@mashb1t Any ETA ?

**Comment by mashb1t** [comment]
I'll most likely be done tomorrow, but review might take a while.

**Comment by VictorZakharov** [comment]
@mashb1t I installed this locally using the latest commit on your branch. It does export metadata, however the format is not compatible with civitai.

I tried to render with prompt "car", here is what civitai parsed as positive prompt:
```
cinematic still car . emotional, harmonious, vignette, 4k epic detailed, shot on kodak, 35mm photo, sharp focus, high budget, cinemascope, moody, epic, gorgeous, film grain, grainy, car, cinematic, epic, beautiful, atmosphere, colorful, vivid, detailed, color, illuminated, built, intricate, elegant, light, confident, full, thoughtful, focused, extremely highly detail, sleek, complex, futuristic, unique, vibrant colors, artistic, cool, awesome, amazing, symmetry, perfect, cute, fabulous, creative, passionate, charming, attractive
```

This looks correct, but negative prompt is messed up:
```
(worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bw, bad photo, bad photography, bad art:1.4), (watermark, signature, text font, username, error, logo, words, letters, digits, autograph, trademark, name:1.2), (blur, blurry, grainy), morbid, ugly, asymmetrical, mutated malformed, mutilated, poorly lit, bad shadow, draft, cropped, out of frame, cut off, censored, jpeg artifacts, out of focus, glitch, duplicate, (airbrushed, cartoon, anime, semi-realistic, cgi, render, blender, digital art, manga, amateur:1.3), (3D ,3D Game, 3D Game Scene, 3D Character:1.1), (bad hands, bad anatomy, bad body, bad face, bad teeth, bad arms, bad legs, deformities:1.3), anime, cartoon, graphic, (blur, blurry, bokeh), text, painting, crayon, graphite, abstract, glitch, deformed, mutated, ugly, disfigured
ADM Guidance: "(1.5, 0.8, 0.3)", CFG scale: 4, Lora hashes: "sd_xl_offset_example-lora_1.0: 4852686128: 0.1", Model: juggernautXL_version6Rundiffusion, Model hash: 1fe6c7ec54, Performance: Speed, Sampler: dpmpp_2m_sde_gpu, Seed: 3988977945423541043, Sharpness: 2, Size: 1152x896, Steps: 30, Version: Fooocus v2.1.864
```

These fields are empty:
image

But main issue - there is no model, so if I post it as it, it will go to limbo and no-one will find it. Basically same issue as before.

**Comment by mashb1t** [comment]
@VictorZakharov Thank you for your feedback. They use a very static reading scheme, so i had to revert the alphabetical key sorting. Everything except sampler should work in the latest commit (still TBD on my side).
I'm currently working on resolving styles for multiline prompts, but other than that and samplers i'm done!

**Comment by VictorZakharov** [comment]
@mashb1t Thanks for fixing it. I checked with civit, it worked fine.
How can I make saving metadata the default? I added this to config.txt:
```
"default_save_metadata_to_images": true,
"default_metadata_scheme": "A1111",
```
But these two settings got cleared as soon as fooocus started. What's going on?

**Comment by mashb1t** [comment]
@VictorZakharov yes, you can indeed enable logging my default using the config. Please check your log output and make sure you're using the lowercase "fooocus" or "a1111" as default_metadata_scheme, see https://github.com/mashb1t/Fooocus/blob/feature/add-metadata-to-files/modules/flags.py#L50-L51

**Comment by VictorZakharov** [comment]
@mashb1t Lowercase or uppercase, it clears the values on start. Basically reverts to the default config.txt.

**Comment by mashb1t** [comment]
Happy to announce that implementation has finished.
Next step is doing internal QA, incl. adjusting the label to prevent such mishaps as @VictorZakharov described with the config + checking multiline prompt compatibility with A1111 again.

**Comment by mashb1t** [comment]
Hey @lllyasviel, 
QA has finished, please thoroughly test and consider also merging the following related PRs:
- https://github.com/lllyasviel/Fooocus/pull/981 (prevents advanced params interference by other users when restoring images by removing them altogether, now all in async jobs args)
- https://github.com/lllyasviel/Fooocus/pull/1932 (to also make metadata available in browser gradio image downloads - if not merged only images in outputs folder will have metadata, not downloaded through browser)

**Comment by VictorZakharov** [comment]
@mashb1t What about samplers?
image

**Comment by mashb1t** [comment]
@VictorZakharov please check if the sampler you've used is in the values of https://github.com/lllyasviel/Fooocus/pull/1940/files#diff-8d388ad9550503ca33fc925141038722382de0352df437d764a83d5b5a8ec0f5R18. Bot all are mappable and supported in Civitai.
This is also the feature which has been implemented last, feedback fro debugging potential issues is welcome.

**Comment by VictorZakharov** [comment]
I used one that is set up by default, "dpmpp_2m_sde_gpu": "",
image

**Comment by mashb1t** [comment]
As you can see in the sampler select of Civitai, this sampler is not supported on their platform, which is also why it's mapped to empty string because there is no equivalent => not filled

**Comment by VictorZakharov** [comment]
Would it make more sense to map to the closest available instead ?

**Comment by mashb1t** [comment]
> Would it make more sense to map to the closest available instead ?

I've re-evaluated the impact and it is minor if not not noticable (source of noise pattern generation cpu vs gpu), so the mapping has been adjusted. See also https://www.reddit.com/r/comfyui/comments/15hayzo/comment/juqcpep/

**Comment by emden09g** [comment]
Love the #1940 Metadata enhancement. Though I would love it even more if the metadata was not only written as a comment (which is fairly userfull as I as I would like to emphasize) but as EXIF-Datafields (which are realy usefull for search and filtering in any photoediting/-organisation software like Lightroom etc.

**Comment by eddyizm** [comment]
Is this ready to pull in to our local fork?

**Comment by mashb1t** [comment]
@eddyizm i'm planning to include this feature in the next release 2.2.0 tomorrow/Monday. Feel free to review.

**Comment by eddyizm** [comment]
Nice! I pulled it down to check it out and see where the merge conflicts are at. Not too much work. 
Looking forward for all the new stuff!

**Comment by VictorZakharov** [comment]
@mashb1t Merge to main when ?

**Comment by mashb1t** [comment]
@VictorZakharov when all ToDo's in https://github.com/lllyasviel/Fooocus/milestone/1 are done and the release candidate has been tested. Feel free to already test develop!

**Comment by Benm678** [comment]
Hi, not sure if this is the right place to comment/report? When using the metadata feature, the metadata is indeed embedded and can be read using alternative readers - but the history log still reports "All images are clean, without any hidden data/meta, and safe to share with others."
image

image


Obviously as the user I know that I clicked the metadata option in the advanced tab, but the log shouldn't report that.

**Comment by mashb1t** [comment]
@Benm678 thanks for the hint. I've already considered removing this line in the log header, but wanted to get some feedback first. As there was no feedback from lllyasviel in the last 2-3 weeks i've decided to keep the line and basically wait for feedback of the community.
The log is only appended to => no dynamic outoput of this line is possible => enabling metadata saving later after initial log creation makes modification of this line in header impossible.
We could integrate JS to find out if one of the images features metadata by a hidden parameter in the log per image, or simply remove the line altogether, which currently is the consideration.
=> planning to remove the line in the next release, but open for feedback!

**Comment by mashb1t** [comment]
@Benm678 => see https://github.com/lllyasviel/Fooocus/pull/2425

**Comment by VictorZakharov** [comment]
@mashb1t I am checking 2.2.0, how do I enter loras? That whole section is gone.
image

**Comment by mashb1t** [comment]
@VictorZakharov this is off-topic, please open a new discussion/issue if needed.
Check if your config has `default_loras` or `default_max_lora_number` is set.

**Pull request merged**
