### PR TITLE
Adjust labels, count from 1

### PR DESCRIPTION
**Pull request by thinkyhead**
- Change label "`Image Number`" to "`Number of Images`"
- Rename `image_number` to `number_of_images`.
- For progress message count Sampling from 1...n.
- For progress message use suffixes `1st`, `2nd`, `3rd`, or `Nth`.

### CODE REVIEW

**Review by sbahlIDBS — CHANGES_REQUESTED** [review]
The variable name nr_images can be changed back to image_number, as the latter seems more explanatory than the former

**Comment by thinkyhead** [comment]
> The variable name `nr_images` can be changed back to `image_number`, as the latter seems more explanatory than the former.

Ah, perhaps I misunderstand the code. Typically a variable named `image_number` will represent the index number of an image in a list of images. If that is what the variable represents, then the name `image_number` is a good choice. If it is meant to represent the total number of images then it should be called something like `total_images`, `images_total`, or `number_of_images`. I followed a common convention shortening it to `nr_images`.

**Comment by thinkyhead** [comment]
Rebased for your convenience.

**Comment by mashb1t** [comment]
Please check if duplicated by https://github.com/lllyasviel/Fooocus/pull/845

**Comment by mashb1t** [comment]
Closing as https://github.com/lllyasviel/Fooocus/pull/845 has been merged!

**Pull request closed without merging**
