### PR TITLE
RestAPI for Fooocus

### PR DESCRIPTION
**Pull request by mrhan1993**
Full Fooocus with Fastapi

### CODE REVIEW

**Comment by mashb1t** [comment]
@mrhan1993 keep up the good work! 👍

**Comment by mrhan1993** [comment]
> @mrhan1993 keep up the good work! 👍

Due to development experience and standardization issues, I am uncertain whether it should be merged into the main branch. Do you have any suggestions on this matter?

**Comment by mashb1t** [comment]
Pro same repository
* one single source of truth
* unified docs
* joint community
* reusability of code / deduplicate code
* release includes both updates for Fooocus and REST API

Contra same repository:
* responsibility for both Websockets and REST API in one repository
* more conflicts in the code
* increased testing effort => increased time to release also for small improvements / fixes

I personally do not have the resources to handle both projects in parallel, so coordination would be key, which then itself can be another disadvantage due to loosing speed on the features, but also an advantage if you're joining Fooocus development in general.

I'm torn between the two options, leaning more towards keeping separate repositories and synching more if you'd be open for that. What do you think?

**Comment by mrhan1993** [comment]
What you said is exactly what I'm worried about. Considering my work situation, the merge might bring you more workload. Although I'm also wavering between the two, I tend to exist as an independent repository. Maybe it's not always the latest version, but it's more free.

**Comment by mashb1t** [comment]
Ok, then let's keep it as is. Wishing you all the best!

**Pull request closed without merging**
