### PR TITLE
Hotfix: use render output per session instead of global

### PR DESCRIPTION
**Pull request by mashb1t**
fixes https://github.com/lllyasviel/Fooocus/issues/713, https://github.com/lllyasviel/Fooocus/issues/501

Use state for worker_outputs in webui and work with parameter in async_worker instead of global outputs.

Tested and working, now shows "initializing" when the other window has been reloaded/closed and WS connection was closed. 

@lllyasviel We might optimize this by setting skip_prompt_processing = true until the current render job is started.

### CODE REVIEW

**Comment by lllyasviel** [comment]
looks like a smart idea 
will take a look soon

**Comment by mashb1t** [comment]
@lllyasviel now includes the code adjustments to automatically stop previous abandoned tasks

**Comment by mashb1t** [comment]
@lllyasviel is it realistic for the changes to be reviewed until end of this week?

**Comment by lllyasviel** [comment]
will be handled in one next version

**Comment by mashb1t** [comment]
I try to keep this MR up-to-date as this is a dealbreaker for multiuser access. Having the feature allows for separate sessions which is mandatory especially when LCM is too fast for the Gradio UI to keep up and users leave the page before the UI thread has finished.

**Comment by lllyasviel** [comment]
unfortunatly this looks a bigger problem and we need to use other ways to fix it. some algorithmic vars are also global.
this can be closed i think

**Comment by mashb1t** [comment]
As currently only one task is processed at a time they may not impact user experience in any / a significant way as resetting them in between jobs should be sufficient.
Which specific vars ar you referring to in this case?

**Comment by lllyasviel** [comment]
added in 2.1.821

**Comment by mashb1t** [comment]
The only remaining behavioural difference is now that tasks will still be processed when the tab is closed / page is reloaded / connection breaks, but this could also be an intended feature as one could queue a large number of images and expect them to be saved to storage, but then closes the tab.
In this PR previous jobs will be stopped by calling the following code, making use of the queue system itself.

generate_clicked
```
if worker.image_number > 0:
    print(f'\nStopping handler for previous task')
    shared.last_stop = 'stop_previous'
    model_management.interrupt_current_processing()
```

async_worker

```
elif shared.last_stop == 'stop_previous':
    print('Previous task stopped')
    break
```

I assume the current behaviour is intended and will close this PR.
Thank you for the implementation, much appreciate it!

**Comment by mashb1t** [comment]
@lllyasviel + another issue still remained which was fixed in this PR, now in a separate MR, see https://github.com/lllyasviel/Fooocus/pull/981

**Pull request closed without merging**
