### PR TITLE
[Feature Request]: Added Clear Button that clears the prompt textbox.

### PR DESCRIPTION
**Pull request by Glought**
A Simple Button that clears the prompt textbox simplify the process when copying and pasting prompts.
foooocus_clear_button

### CODE REVIEW

**Comment by mashb1t** [comment]
This is a won't do as the button is not in line with the design philosophy as well as it doesn't offer much benefit as one can just delete the prompt. Feel free to keep it in your fork though and optimize by directly returning empty steing without variable allocation.

**Comment by Glought** [comment]
Honestly what is the design philosophy I can't find any info on it.

**Comment by mashb1t** [comment]
It's not a document but Fooocus aims to be the open source alternative to Midjourney, and they don't have a clean prompt button as this simply is your input field in discord. Also the button doesn't integrate seamlessly in the UI as it's not next to already existing buttons but in a line of checkbox elements.

**Comment by Glought** [comment]
ok that makes sense. I placed the button there because I didn't want to squish the prompt textbox. I'll just keep my changes to my fork.

**Pull request closed without merging**
