### PR TITLE
Add ability to load checkpoints and loras from multiple locations

### PR DESCRIPTION
**Pull request by dooglewoogle**
I have models on different drives (and network storage) for the different levels of storage or speed required, and still wanted to be able to access them all. 

The config for paths can either be a string, or a list, like so:

path_checkpoints: "C:\\Location1",
"path_checkpoints": [
        "C:\\Location1",
        "D:\\Location2",
    ],

### CODE REVIEW

**Comment by yorkane** [comment]
We need this!

**Comment by jclevet** [comment]
You can use a symbolik link to share a checkpoint folder between multiple UI.

**Comment by kyeno** [comment]
> You can use a symbolik link to share a checkpoint folder between multiple UI.

That is exactly what I do.
I guess Windows guys can't. :D

**Comment by jclevet** [comment]
On Windows, you can use Link Shell Extension
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html
This tool can create symbolik link without needing to type command lines

**Pull request merged**
