### PR TITLE
add dockerfile, update readme

### LINKED ISSUE #1138: add docker image

### PR DESCRIPTION
**Pull request by realies**
could be used to fix #1138 if the image is published in a container image repository

### CODE REVIEW

**Comment by realies** [comment]
> running as root is a bad idea check this : [Dockerfile](https://github.com/superpoussin22/Fooocus/blob/features/Dockerfile)

what's bad about it?
ps: why do you install the extra dependencies?

**Comment by Hummenix** [comment]
@realies 
> what's bad about it? 

Quite simply the same reason you shouldn't run any process as root if not absolutely necessary. It is possible to break out of a docker container (look up "docker privilege escalation/breakout" for more info), or it could be misconfigured and misbehave leading to issues with the host system. 
Yes, docker is pretty well isolated, but the risk is still there, and there is no benefit from running as root. It's just a secure practice.

**Comment by realies** [comment]
I've reduced the privileges in the latest commit.
@superpoussin22, wondering why your Dockerfile installs more dependencies.

**Comment by realies** [comment]
Thanks, @matiboux. I've applied your suggestions in the latest commit.

**Comment by whitehara** [comment]
I also made docker related files and send PR as #1418 
Shoud I merge this PR?

**Comment by realies** [comment]
> I also made docker related files and send PR as #1418 
> Shoud I merge this PR?

Dunno man, all other Dockerfiles I've seen so far look more complex without any (obvious to me) reason.

**Comment by whitehara** [comment]
> > I also made docker related files and send PR as #1418
> > Shoud I merge this PR?
> 
> Dunno man, all other Dockerfiles I've seen so far look more complex without any (obvious to me) reason.

OK. Your Dockerfile is almost the same as mine. But my PR has other feature about environment variables.
So I think it depends on which is preferred by the repo owner to merge.

**Comment by mashb1t** [comment]
https://github.com/lllyasviel/Fooocus/pull/1418 is now more mature than this PR, please consider contributing your ideas there.

**Pull request closed without merging**
