### PR TITLE
Added translation file in Russian language

### PR DESCRIPTION
**Pull request by SamirDyuran**
Hello, I've finished translating and adapting for the Russian language. Please accept it into the main branch. In the future, I will continue to update and refine the translation. Thank you.

### CODE REVIEW

**Comment by ke1ne** [comment]
Russia is a terrorist state! No support to genocider and world security obstacler!

**Comment by scroogemcfawk** [comment]
Good job! However, you have some missing keys (like ```"Click or Upload"``` and ```"Drop Image Here"```) in your dictionary.

**Comment by SamirDyuran** [comment]
> Хорошая работа! Однако в вашем словаре отсутствуют некоторые ключи (например, `"Click or Upload"`и `"Drop Image Here"`).

Thank you. You're right. I missed a few points, not intentionally. If it's accepted into the main branch, I'll continue to supplement, correct, and adapt the translation further. )

**Comment by SamirDyuran** [comment]
> Good job! However, you have some missing keys (like `"Click or Upload"` and `"Drop Image Here"`) in your dictionary.

Thank you. You're right. I missed a few points, not intentionally. If it's accepted into the main branch, I'll continue to supplement, correct, and adapt the translation further. )

**Comment by Djalil1976** [comment]
Здравствуйте, Самир!

Отличная идея с переводом на русский язык Fooocus! Где можно скачать ваш файл? Заранее благодарю.

**Comment by SamirDyuran** [comment]
Я скоро выложу отдельно на гитхабе и пришлю вам ссылку

чт, 4 янв. 2024 г. в 11:54, Djalil1976 ***@***.***>:

**Comment by SamirDyuran** [comment]
https://github.com/SamirDyuran/Fooocus-RU

**Comment by Djalil1976** [comment]
Благодарю, Самир!

**Pull request closed without merging**
