### PR TITLE
user upload inpaint mask

### PR DESCRIPTION
**Pull request by xingren23**
Sometimes, precise masks are required, and it's not possible to achieve them through manual drawing. Allowing users to upload generated masks can make redrawing more accurate. Users can use tools like Photoshop (PS) or ComfyUI to create masks.

Two image selection boxes are provided: one on the left to upload the inpainting image and another on the right to upload the inpainting mask. Users can also manually draw a mask on the left-side image, with priority given to the manually drawn mask.

image

Closes https://github.com/lllyasviel/Fooocus/issues/1036

### CODE REVIEW

**Comment by XiaoCC** [comment]
非常需要的功能，太棒了

**Comment by giovanninicol** [comment]
definitely a necessary feature!

**Comment by XiaoCC** [comment]
什么时候能合并主分支啊

**Comment by lllyasviel** [comment]
we will try to have it before 2.1.8 and see if we can still keep the UI simplicity, perhaps being enabled by an option in dev tool

**Comment by XiaoCC** [comment]
> we will try to have it before 2.1.8 and see if we can still keep the UI simplicity, perhaps being enabled by an option in dev tool

Fooocus version: 2.1.805 还是没有inpaint mask功能

**Comment by XiaoCC** [comment]
> we will try to have it before 2.1.8 and see if we can still keep the UI simplicity, perhaps being enabled by an option in dev tool我们将尝试在 2.1.8 之前使用它，看看我们是否仍然可以保持 UI 的简单性，也许可以通过开发工具中的选项启用

还没有更新哦

**Comment by XiaoCC** [comment]
啥时候能更新mask功能啊

**Comment by xhoxye** [comment]
It's easy to use, and it can be used for new versions with a little modification.
很好用，修改一下就可以用于新版本

**Comment by XiaoCC** [comment]
> we will try to have it before 2.1.8 and see if we can still keep the UI simplicity, perhaps being enabled by an option in dev tool

请问以下什么时候能加入上传蒙版功能？

**Comment by mashb1t** [comment]
Closing as https://github.com/lllyasviel/Fooocus/pull/1645 has already been merged. Feel free to reopen if you think that this feature has some further benefits over the merged one.

**Pull request closed without merging**
