### PR TITLE
Allow images in log.html to be opened by clicking on them

### PR DESCRIPTION
**Pull request by MuAlphaOmegaEpsilon**
Sometimes when scrolling through the log.html file you just want to look at a given picture with more detail.
Being able to simply click on the image to open it makes things simpler.

I also removed a residual closing ‘p‘ tag in the process.

### CODE REVIEW

**Comment by Hangover3832** [comment]
Indeed, the p tags are a bit messy. May be also the p tag in the parameter list should be replaced with a simple <br> to keep the text more compact. Furthermore, Im not sure if this makes sense either inside the img tag: width=auto height=100% and style=\"height:auto;max-width:512px\". The closing </img> is also not necessary.

**Comment by lllyasviel** [comment]
am willing to change but it seems a few projects have hard coded the current log format so we only change it when the trade-off outweigh highly enough
but will review later

**Comment by MuAlphaOmegaEpsilon** [comment]
> Indeed, the p tags are a bit messy. May be also the p tag in the parameter list should be replaced with a simple `<br>` to keep the text more compact. Furthermore, I'm not sure if this makes sense either inside the img tag: width=auto height=100% and style="height:auto;max-width:512px". The closing `</img>` is also not necessary.

Totally agree, will try to improve a bit on the compactness.

**Comment by MuAlphaOmegaEpsilon** [comment]
> am willing to change but it seems a few projects have hard coded the current log format so we only change it when the trade-off outweigh highly enough but will review later

I have other ideas in mind to drastically improve the aesthetics and functionality of the log.html file when opened from the browser, let me know if it's worth to explore already that space to make a more meaningful breaking change.

In case you want to avoid breaking tools that depend on the current format, I can arrange a secondary improved html file, and in the meantime we can mark the previous one as deprecated and allow everybody depending on it to move to transition to the new one.

**Comment by Hangover3832** [comment]
What about outputting a separate json? Other projects could stick on this instead on html in the future.

**Comment by lllyasviel** [comment]
please refer to https://github.com/lllyasviel/Fooocus/pull/1482

**Pull request closed without merging**
