### PR TITLE
feat: adds preview overlay for styles

### PR DESCRIPTION
**Pull request by crohrer**
closes https://github.com/lllyasviel/Fooocus/issues/1743

this includes sample images from https://github.com/lllyasviel/Fooocus/pull/1749 and displays them in an overlay on mouseover.

### CODE REVIEW

**Review by mashb1t — APPROVED** [review]
lgtm, 100% implements requested enhancement in https://github.com/lllyasviel/Fooocus/issues/1743 👍

**Comment by diaolulu1** [comment]
I am unable to display images here, only a transparent box is shown.

360截图20240106010346546

**Comment by mashb1t** [comment]
@docppp i don't think that's possible for @crohrer without giving write access to your repo.
There are a few options:

1. you add @crohrer as maintainer to your repository (worst option)
2. you add the remote `git@github.com:crohrer/Fooocus.git` or https equivalent to your local git repository and merge the main branch into yours + resolve conflicts (best option)
3. you c&p the changes of this PR into yours, loosing the relation to the author in the process.
4. a collaborator / reviewer does option 2

**Comment by diaolulu1** [comment]
> @diaolulu1 please check your network tab, this may have to do with slow internet speed between you and the server (if you're using Fooocus remotely). If that isn't the case please check if the meta `samples-path` is correctly set to your project root, see screenshot attached:
> 
> Screenshot 2024-01-05 at 18 19 24

**Comment by mashb1t** [comment]
> @diaolulu1 please check your network tab, this may have to do with slow internet speed between you and the server (if you're using Fooocus remotely). If that isn't the case please check if the meta `samples-path` is correctly set to your project root, see screenshot attached:
> 
> Screenshot 2024-01-05 at 18 19 24

@diaolulu1 I see your code is unchanged and should work. Please check the browser network tab  for any requests and the browser page source code at samples-path to help debug this.

**Comment by diaolulu1** [comment]
> > @diaolulu1 please check your network tab, this may have to do with slow internet speed between you and the server (if you're using Fooocus remotely). If that isn't the case please check if the meta `samples-path` is correctly set to your project root, see screenshot attached:
> > Screenshot 2024-01-05 at 18 19 24
> 
> @diaolulu1 I see your code is unchanged and should work. Please check the browser network tab for any requests and the browser page source code at samples-path to help debug this.

I apologize for not understanding you earlier, but now I do. I have checked the webpage source code, and the address is correct. Using that address, I was able to successfully open the image in the file explorer.

**Comment by mashb1t** [comment]
@diaolulu1 i can confirm that it is not working on Windows as the paths are wrong.
@crohrer please ensure both Windows and Linux/MacOS paths are working correctly for preview images.

**Review by mashb1t — CHANGES_REQUESTED** [review]
@diaolulu1 i can confirm that it is not working on Windows as the paths are wrong.
@crohrer please ensure both Windows and Linux/MacOS paths are working correctly for preview images.

**Comment by mashb1t** [comment]
@diaolulu1 fixed & tested for both Windows and MacOS, please check again

**Comment by hswlab** [comment]
Do I need to download a new version of fooocus, or is this tool able to update this changes automatically?

**Comment by mashb1t** [comment]
@hswlab Fooocus will be updated automatically if you're using entry_with_update.py, but you'll only be able to use this feature this way after the PR has successfully been reviewed and merged.

**Comment by JulienZLQ** [comment]
After trying, it can meet the preview effect, but after using a non-native language, the inconsistent page text and the picture file name will not take effect. It cannot be automatically associated and matched from the source. I need to change the file name of the picture one by one.

**Comment by diaolulu1** [comment]
> @diaolulu1 fixed & tested for both Windows and MacOS, please check again

Thank you very much for your modification; the program is now running normally, but only in English. If switched to Chinese or other languages, it cannot adapt properly. The image filenames need to be changed to the corresponding language, which cannot guarantee universality.

**Comment by crohrer** [comment]
I implemented support for other languages. I hope it works for everyone

**Comment by docppp** [comment]
Changes from this PR are now reflected in https://github.com/lllyasviel/Fooocus/pull/1749

**Comment by simartem** [comment]
LEGEND!

**Review by mashb1t — APPROVED** [review]
Thank you for the adjustment, works for me on both Windows and MacOS using various different languages, incl. default.

**Comment by diaolulu1** [comment]
Great！ thanks for you work！

**Comment by diaolulu1** [comment]
Great,！thanks for your job！

**Review by akhilesh-s — APPROVED** [review]

**Review by docppp — CHANGES_REQUESTED** [review]
If preview overlay will be merged without log-like page, log.html should be removed.

**Comment by mashb1t** [comment]
@docppp i don't see how this preview overlay PR is related to log.html files, daily logs of generated images & configs (which can be turned off using `--disable-image-log`). Please elaborate.

**Comment by docppp** [comment]
@mashb1t Not exactly, as per my understanding, the is no decision yet if only tooltip (this PR) or [tooltip with  ](https://github.com/lllyasviel/Fooocus/pull/1749) will be merged. If it happens, that this one get the green light, then sdxl_styles/samples/log.html file is useless.

**Comment by lllyasviel** [comment]
i am going to merge.
but still need to consider that increased file size of this repo since the auto update will pull all files.
i will see of i can make extra files smaller or so

**Comment by simartem** [comment]
> ged without log-like

I dont if its someway technically possible (just like downloading the default model after the code is run on local) but instead of pulling all sample style images, script will download external sample/images from an external cloud link and put them in the required folder on first run, after user upgraded to new version. So that the original software size will remain same.

**Comment by mashb1t** [comment]
@lllyasviel i've scale down the images to Retina resolution (2x displayed res), fixed the aspect ratio and applied jpeg compression. This reduces the file size from 19,6MB to 3,4MB.

**Comment by xhoxye** [comment]
> @lllyasviel i've scale down the images to Retina resolution (2x displayed res), fixed the aspect ratio and applied jpeg compression. This reduces the file size from 19,6MB to 3,4MB.

Is it possible to save small pictures but display large ones?

**Comment by mashb1t** [comment]
> Is it possible to save small pictures but display large ones? 130 x100 px ,Is this size too small?

Yes, you can bump the css width and height e.g. x2, but keep in mind that quality will decrease from higher res. than 260x200.
In general, it's best practice to keep images with x2 resolution than displayed (retina).

I personally would really like to keep it small (current 130x100px):
* saves disk space
* is sufficient to get a preview
* great on mobile devices / viewports

**Review by lllyasviel — APPROVED** [review]

**Comment by mashb1t** [comment]
@lllyasviel Is it intended that the images are now smaller in dimensions and >200% larger in file size? Did you compress the images after downscaling?

> In general, it's best practice to keep images with x2 resolution than displayed (retina).

As mentioned, it is best practice to keep images x2 the display size for upscaled outputs, so 256x256 would be ideal here when displaying as 128x128px.

**Comment by mashb1t** [comment]
Some files were not correctly renamed, please merge the changes of https://github.com/lllyasviel/Fooocus/pull/1809

**Comment by GoldMath** [comment]
Thanks for the addition, I just noticed that small issue reported here with the thumbnails at the bottom at the windows
> Minor UI issue with image preview in Style when mouse hover at the bottom #1816

**Comment by Kyl329** [comment]
can we change the main realistic model to the Juggernaut V8? makes it easier for colab users

**Pull request merged**
