### PR TITLE
Add custom styles using json file

### PR DESCRIPTION
**Pull request by TimothyAlexisVass**
Allows users to extend the styles array by adding style dicts to custom_styles.json

### CODE REVIEW

**Comment by TimothyAlexisVass** [comment]
Seems like an easy thing to fix...

**Comment by lllyasviel** [comment]
will merge in next release

**Review by lllyasviel — APPROVED** [review]

**Comment by lllyasviel** [comment]
hi you may consider 
add try catch to loading so that it does not crash when json file is misedited out of format
and add that file to gitignore so that it will not be cleared by auto update system

**Comment by TimothyAlexisVass** [comment]
Okay I've refactored according to your request.

**Pull request closed without merging**
